import { Code, Server, Globe, Cpu, Brain, Building2, Briefcase, Laptop, Sparkles, GraduationCap, Users } from 'lucide-react';

export const TECH_CATEGORIES = [
  {
    key: 'frontend',
    icon: Globe,
    skills: [
      { name: 'React', level: 90 },
      { name: 'TypeScript', level: 90 },
      { name: 'Vite', level: 85 },
      { name: 'TailwindCSS', level: 85 },
      { name: 'Module Federation', level: 75 },
      { name: 'Next.js', level: 70 },
      { name: 'TanStack Query', level: 70 },
      { name: 'Storybook', level: 65 },
    ],
  },
  {
    key: 'backend',
    icon: Server,
    skills: [
      { name: 'Supabase', level: 90 },
      { name: 'Edge Functions', level: 85 },
      { name: 'Node.js', level: 80 },
      { name: 'PostgreSQL', level: 75 },
      { name: 'Zod', level: 75 },
      { name: 'Hono + Bun', level: 70 },
      { name: 'NestJS', level: 55 },
      { name: 'ClickHouse', level: 40 },
      { name: 'RabbitMQ', level: 35 },
    ],
  },
  {
    key: 'ai',
    icon: Sparkles,
    skills: [
      { name: 'Claude API', level: 85 },
      { name: 'MCP servers', level: 85 },
      { name: 'AI agents', level: 80 },
      { name: 'LLM integration', level: 75 },
      { name: 'n8n', level: 60 },
      { name: 'OpenAI API', level: 55 },
    ],
  },
  {
    key: 'devops',
    icon: Cpu,
    skills: [
      { name: 'Git & GitHub', level: 90 },
      { name: 'Vercel', level: 85 },
      { name: 'GitHub Actions', level: 80 },
      { name: 'Docker', level: 65 },
      { name: 'Linux / VPS', level: 65 },
      { name: 'Dokploy', level: 60 },
      { name: 'AWS', level: 30 },
    ],
  },
  {
    key: 'quality',
    icon: Brain,
    skills: [
      { name: 'Code review', level: 85 },
      { name: 'Technical docs', level: 80 },
      { name: 'Vitest', level: 70 },
      { name: 'Playwright', level: 65 },
      { name: 'Figma', level: 40 },
    ],
  },
  {
    key: 'web3',
    icon: Code,
    skills: [
      { name: 'ERC-20 / ERC-721', level: 50 },
      { name: 'Base / Scroll', level: 50 },
      { name: 'Solidity', level: 45 },
      { name: 'Chainlink CRE / CCIP', level: 45 },
      { name: 'Foundry', level: 35 },
      { name: 'Solana / Anchor', level: 35 },
      { name: 'Rust', level: 25 },
    ],
  },
  {
    key: 'collab',
    icon: Users,
    skills: [
      { name: 'Daily / Scrum', level: 90 },
      { name: 'Code & PR reviews', level: 85 },
      { name: 'Mentoring', level: 85 },
      { name: 'Pair programming', level: 80 },
      { name: 'UI/UX design', level: 60 },
    ],
  },
];

export const EXPERIENCE_DATA = [
  {
    key: 'dfl',
    company: 'DevFellowship',
    current: true,
    stack: ['React', 'TypeScript', 'Module Federation', 'Hono', 'Bun', 'Supabase', 'PostgreSQL', 'Edge Functions', 'MCP', 'Claude API', 'GitHub Actions', 'Docker', 'Playwright'],
    logo: '/DevFelloShip.png',
    icon: Briefcase,
    website: 'https://devfellowship.com',
  },
  {
    key: 'revera',
    company: 'Revera',
    current: true,
    stack: ['React', 'TypeScript', 'Node.js', 'Supabase', 'PostgreSQL', 'TailwindCSS', 'Claude API', 'AI agents', 'MCP'],
    logo: '/Revera.png',
    icon: Sparkles,
    website: 'https://revera.dev/',
  },
  {
    key: 'itera',
    company: 'Itera',
    current: true,
    stack: ['Live classes', 'JavaScript', 'Programming logic', 'Mentoring'],
    logo: '/Itera.svg',
    icon: GraduationCap,
    website: 'https://iterahq.dev/',
  },
  {
    key: 'educar',
    company: 'Instituto Educar+',
    current: true,
    stack: ['Teaching', 'JavaScript', 'HTML', 'CSS', 'Git & GitHub', 'Vercel', 'Mentoring'],
    logo: '/EducarMais.webp',
    icon: GraduationCap,
    website: 'https://institutoeducarmais.org/',
  },
  {
    key: 'mm',
    company: 'M&M Informática',
    current: false,
    stack: ['ERP support', 'Incident triage', 'Customer support'],
    logo: '/MMIcon.png',
    icon: Laptop,
    website: 'https://mminfo.me',
  },
  {
    key: 'prefeitura',
    company: 'Prefeitura de Marialva',
    current: false,
    stack: ['IT support', 'Hardware maintenance', 'Operating systems'],
    logo: '/prefeitura.png',
    icon: Building2,
    website: 'https://www.marialva.pr.gov.br',
  },
];

export const EVENTS_DATA = [
  { name: 'Web3 Experts Brazil', type: 'conference', date: 'Jun 2026', location: 'São Paulo, BR', ecosystems: ['Avalanche', 'Klever'], url: 'https://www.web3experts.com.br/' },
  { name: 'Hackanation 2026 · TokenNation', type: 'hackathon', date: 'May 2026', location: 'São Paulo, BR', ecosystems: ['Binance', 'Chainlink', 'Solana'], url: 'https://taikai.network/en/TokenNation/hackathons/Hackanation2026/overview' },
  { name: 'DevConnect · Tierra de Buidlers 2025', type: 'hackathon', date: 'Nov 2025', location: 'Buenos Aires, AR', ecosystems: ['Scroll', 'Ethereum'], url: 'https://taikai.network/en/ethargentina/hackathons/tierra-de-buidlers-2025/overview' },
  { name: 'ETH Latam 2025', type: 'hackathon', date: 'Aug 2025', location: 'São Paulo, BR', ecosystems: ['Base', 'Ethereum'], url: 'https://taikai.network/en/ethsamba/hackathons/ethlatam25/overview' },
];
